### ISSUE TITLE
Реализуйте тесты ко всем открытым методам класса

### ISSUE THREAD

**Issue by simplydesigner** [ksorskiy/complex#4]

**Comment by ksorskiy** [comment]
Сделал тесты для конструктора с параметрами, операций сложения и вычитания.

У меня возникло 2 вопроса.
1. где посмотреть документацию по синтаксису `SCENARIO`? на сайте [трэвиса](https://docs.travis-ci.com/) много информации касательно развертки и запуска, но ничего (!!) не сказано про синтаксис написания тестов. поэтому я не могу написать тесты для метода `display()`, так как он выводит результат в консоль, а я не знаю как получить доступ к потоку вывода внутри scenario
2. каким образом реализовать обработку исключений в методах? если, например, я создам объект не из чисел: `Complex example('jfds', 'ds')`. можно было бы сделать проверку на тип параметров и в случае, если `typeid(real_).name() != 'double'`, то выводить в консоль ошибку. но опять же - я не умею читать консоль из файла тестов.

**Comment by ksorskiy** [comment]
простите за вопрос, разобрался что это catch.hpp
в общем-то первый вопрос отпал (display() не нужно просто тестировать наверное), остался только второй.

**Comment by simplydesigner** [comment]
Если вы напишите Complex example('jfds', 'ds'), то у Вас просто программа не скомпилируется.
